variable "kubeconfig_path" {
  description = "Path to the kubeconfig generated by the OCI CLI."
  type        = string
}

variable "github_repository" {
  description = "Git repository containing the Helm chart."
  type        = string
  default     = "https://github.com/douglas85rj/dgsite.git"
}
